pre-release-replacements = [
    {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
    {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
    {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
    {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
    {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/eldruin/{{crate_name}}-rs/compare/{{tag_name}}...HEAD", exactly=1},
    {file="README.md", search="pwm-pca9685 = . version = .*", replace="{{crate_name}} = { version = \"{{version}}\", features = [\"async\"] }"},
    {file="src/lib.rs", search="pwm-pca9685 = . version = .*", replace="{{crate_name}} = { version = \"{{version}}\", features = [\"async\"] }"},
]